### ISSUE TITLE
lets align meta by delimiter

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/send-fs-neo-org#89]
![image](https://github.com/nspcc-dev/send-fs-neo-org/assets/14617699/80430020-a66c-447e-8e70-0e3e790f0116)

![image](https://github.com/nspcc-dev/send-fs-neo-org/assets/14617699/a447ed78-e89c-467c-8a22-ff55a70e8c55)

**Comment by mike-petrov** [comment]
@532910 `AccessDenied` for all files above, I see only alt text: `image`

**Comment by roman-khimov** [comment]
@532910, please update with some up to date feedback. I'm not sure if this one should closed or there is something to do here.

**Comment by mike-petrov** [comment]
Current version:
<img width="1440" alt="image" src="https://github.com/nspcc-dev/send-fs-neo-org/assets/32885629/d7e0352a-37ab-4616-a769-7bde92232a1a">

**Comment by mike-petrov** [comment]
@532910 is negotiating with github to unlock screenshots, we don't know when this will be resolved

**Comment by roman-khimov** [comment]
Sufficient for now.
